Android 12 support
romellfudi/FudiNFC pull request #8
Opened 2022-03-21 11:46 UTC by zigapovhe

Added support for Android12. Fixes issue https://github.com/romellfudi/FudiNFC/issues/7

2022-03-21 12:37 UTC, romellfudi commented
Hi @zigapovhe , do you test in previous version for instance 9 , 10, 11?

2022-03-21 12:41 UTC, zigapovhe commented
> Hi @zigapovhe , do you test in previous version for instance 9 , 10, 11?

I didn't even properly test it for Android 12, that's why I've sent you an email. Not sure if you understand me correctly. 🙂

2022-03-24 13:47 UTC, romellfudi requested changes
I can't build the project, Does it necessary to update kotlin & compileSdkVersion versions?

2022-03-24 13:48 UTC, romellfudi commented on app/build.gradle
> +    compileSdkVersion 31
I can't build the project, Does it necessary to update kotlin & compileSdkVersion versions?

2022-03-24 13:48 UTC, romellfudi commented on build.gradle
> +    ext.kotlin_version = '1.6.10'
I can't build the project, Does it necessary to update kotlin & compileSdkVersion versions?

2022-03-24 13:48 UTC, romellfudi commented on fudi-nfc/build.gradle
> +    compileSdkVersion 31
I can't build the project, Does it necessary to update kotlin & compileSdkVersion versions?

2022-03-25 00:56 UTC, romellfudi commented
@zigapovhe  please indicate your distribution Version:

`distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip`

2022-03-26 18:54 UTC, romellfudi commented
@zigapovhe  I dont have a Android 12 and the changes does not work on Android 10. Thus I will crate a release branch with your PR

2022-03-26 19:06 UTC, romellfudi approved these changes
On the grounds the PR is only for Android 12 devices, thus it works correctly

2022-03-26 19:06 UTC, romellfudi commented on fudi-nfc/src/main/java/com/romellfudi/fudinfc/gear/NfcAct.kt
> +            PendingIntent.FLAG_MUTABLE
Why didn't you add a clause condition for higher Build.VERSION_CODES.M?

2022-03-26 19:06 UTC, merged

2022-03-26 19:07 UTC, romellfudi commented
Thanks very much @zigapovhe